---
install:
  - cpanm --notest --skip-satisfied Class::Tiny Config::AutoConf Module::Pluggable::Object Carp App::mymeta_requires
  - perl Makefile.PL
  - make manifest
  - mymeta-requires --runtime --build --test --configure --develop --recommends --suggests | cpanm
language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
